Первая версия кода мини-приложения ананалога Кинопоиска
ivan-nizalzov/java-filmorate pull request #1
Opened 2023-01-16 20:08 UTC by ivan-nizalzov

Comment #1

2023-01-17 18:30 UTC, andrew-larkin requested changes
Привет! Очень здорово, код написан действительно хорошо. В паре мест поправить и мы будем готовы двигаться дальше.

2023-01-17 18:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService = new FilmService();
инициализировать внедренный объект с помощью конструктора не требуется, спринг сделает это сам во время запуска приложения. Но чтобы он точно это сделал, нам нужно добавить над классом аннотацию @RequiredArgsConstructor

2023-01-17 18:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findAllFilms();
добавь сюда тоже логгирование, пожалуйста

2023-01-17 18:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
аналогичные правки как и в FilmController

2023-01-17 18:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private Film validateFilm(Film film) {
очень хорошо!

2023-01-17 18:30 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
в тестах у объявляемых переменных также стоит указывать модификатор доступа

2023-01-18 15:27 UTC, ivan-nizalzov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findAllFilms();
Логгирование добавил

2023-01-18 15:27 UTC, ivan-nizalzov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Добавил

2023-01-18 15:29 UTC, ivan-nizalzov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
Исправил

2023-01-18 16:37 UTC, ivan-nizalzov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService = new FilmService();
Исправил, внес аннотацию в FilmService, FilmController, UserService, UserController.

2023-01-23 16:26 UTC, merged