feat: added embedded database H2
ivan-nizalzov/java-filmorate pull request #5
Opened 2023-02-26 19:50 UTC by ivan-nizalzov

Added embedded database H2 using JdbcTemplate.

2023-02-26 20:30 UTC, andrew-larkin requested changes
Привет! Хорошая реализация, несколько правок и можно будет приступать к групповому проекту.

2023-02-26 20:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public UserController(UserService userService) {
здесь тоже можно @RequiredArgsConstructor

2023-02-26 20:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findByID(userId);
эти проверки лучше выделить в отдельные приватные методы

2023-02-27 19:27 UTC, ivan-nizalzov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public UserController(UserService userService) {
Добавил аннотацию

2023-02-27 20:02 UTC, ivan-nizalzov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.findByID(userId);
Проверки убрал в отдельные приватные методы

2023-03-01 17:11 UTC, merged